Repository Azure/caf-terraform-landingzones, pull requests merged in 2020-12, with the labels that each got.

#110 Update azurerm and update tag_inheritance from launchpad
  landingzones/caf_foundations/locals.remote_tfstates.tf
  landingzones/caf_foundations/main.tf
  landingzones/caf_launchpad/add-ons/azure_devops/main.tf
  landingzones/caf_launchpad/add-ons/azure_devops_agent/main.tf
  landingzones/caf_launchpad/landingzone.tf
  landingzones/caf_launchpad/main.tf
  landingzones/caf_networking/landingzone.tf
  landingzones/caf_networking/locals.remote_tfstates.tf
  landingzones/caf_networking/main.tf
  landingzones/caf_networking/variables.tf
  landingzones/caf_shared_services/landingzone.tf
  landingzones/caf_shared_services/locals.remote_tfstates.tf
  landingzones/caf_shared_services/main.tf
Labels: bug, enhancement

#108 Update readme.md
  landingzones/caf_launchpad/readme.md
Labels: documentation

#119 fix inherit tags in devops
  landingzones/caf_launchpad/add-ons/azure_devops/locals.remote_tfstates.tf
Labels: bug

#120 Fix broken link caf_foundations landing zone
  README.md
Labels: documentation

#121 Update 2012.1.0
  landingzones/caf_foundations/dynamic_secrets.tf
  landingzones/caf_foundations/landingzone.tf
  landingzones/caf_foundations/locals.remote_tfstates.tf
  landingzones/caf_launchpad/add-ons/azure_devops/solution.tf
  landingzones/caf_launchpad/add-ons/azure_devops_agent/dynamic_secrets.tf
  landingzones/caf_launchpad/add-ons/azure_devops_agent/solution.tf
  landingzones/caf_launchpad/dynamic_secrets.tf
  landingzones/caf_launchpad/landingzone.tf
  landingzones/caf_networking/landingzone.tf
  landingzones/caf_shared_services/landingzone.tf
  landingzones/caf_shared_services/vm_extensions.tf
Labels: breaking-change
