Repository Azure/caf-terraform-landingzones, pull requests merged in 2021-11, with the labels that each got.

#269 Add Virtual Subnets sub module
  caf_launchpad/landingzone.tf
  caf_solution/landingzone.tf
  caf_solution/local.networking.tf
  caf_solution/variables.networking.tf
Labels: pending module update

#270 Update example 106 - virtual wan structure
  caf_solution/scenario/networking/106-hub-virtual-wan-firewall/peerings.tfvars
  caf_solution/scenario/networking/106-hub-virtual-wan-firewall/virtual_hubs.tfvars
  caf_solution/scenario/networking/106-hub-virtual-wan-firewall/virtual_wan.tfvars
Labels: bug

#260 Use correct attribute name for ACR
  caf_solution/local.remote.tf
Labels: bug

#265 Remove unused var from azure_devops_v1
  caf_solution/add-ons/azure_devops_v1/scenario/200-contoso_demo/projects.tfvars
  caf_solution/add-ons/azure_devops_v1/variables.tf
Labels: bug

#266 Support aad_apps for AZDO service endpoints
  caf_solution/add-ons/azure_devops_v1/azdo_service_endpoint.tf
Labels: enhancement

#259 Add support for application_gateway_applications_v1
  caf_solution/local.networking.tf
  caf_solution/local.remote.tf
  caf_solution/variables.networking.tf
Labels: bug

#272 update version and remove unused var
  caf_solution/add-ons/azure_devops_agent/local.azuread.tf
  caf_solution/add-ons/azure_devops_agent/solution.tf
  caf_solution/add-ons/azure_devops_agent/variables.tf
Labels: bug
