Repository Azure/caf-terraform-landingzones, pull requests merged in 2021-06, with the labels that each got.

#195 Add launchpad_identities for azuread groups and msi from launchpad to propagate
  caf_launchpad/output.tf
  caf_launchpad/variables.tf
  caf_solution/add-ons/aks_applications/locals.remote_tfstates.tf
  caf_solution/local.remote.tf
  caf_solution/locals.remote_tfstates.tf
  caf_solution/output.tf
  caf_solution/variables.tf
Labels: enhancement

#197 Add vmss to landingzone
  caf_solution/local.compute.tf
  caf_solution/variables.compute.tf
Labels: enhancement

#187 May 2021 updates
  .devcontainer/docker-compose.yml
  .github/workflows/landingzones-tf13.yml
  .github/workflows/landingzones-tf14.yml
  .github/workflows/landingzones-tf15.yml
  README.md
  caf_launchpad/landingzone.tf
  caf_launchpad/main.tf
  caf_launchpad/output.tf
  caf_launchpad/variables.tf
  caf_solution/add-ons/caf_eslz/archetype_config_overrides.tf
  caf_solution/add-ons/caf_eslz/custom_landing_zones.tf
  caf_solution/dynamic_secrets.tf
  caf_solution/landingzone.tf
  caf_solution/local.cloud.tf
  caf_solution/local.compute.tf
  caf_solution/local.remote.tf
  caf_solution/locals.remote_tfstates.tf
  caf_solution/main.tf
  caf_solution/output.tf
  caf_solution/variables.cloud.tf
  caf_solution/variables.compute.tf
  caf_solution/variables.tf
  caf_solution/vm_extensions.tf
  documentation/README.md
  documentation/getting_started/getting_started.md
Labels: enhancement

#199 Fixing diagnostics output for caf_solution
  caf_solution/output.tf
Labels: bug

#204 docs: update rover command file path
  caf_launchpad/readme.md
Labels: documentation

#209 Remote LZ support for extensions
  caf_solution/vm_extensions.tf
Labels: bug

#207 Added Hashicorp Vault add-on to caf landing zone
  caf_solution/add-ons/hashicorp_vault_secrets/README.md
  caf_solution/add-ons/hashicorp_vault_secrets/backend.azurerm
  caf_solution/add-ons/hashicorp_vault_secrets/local.remote_tfstates.tf
  caf_solution/add-ons/hashicorp_vault_secrets/main.tf
  caf_solution/add-ons/hashicorp_vault_secrets/providers.tf
  caf_solution/add-ons/hashicorp_vault_secrets/scenario/100-simple-hashicorp-vault-secrets/configuration.tfvars
  caf_solution/add-ons/hashicorp_vault_secrets/secret/variables.tf
  caf_solution/add-ons/hashicorp_vault_secrets/secret/vault_secret.tf
  caf_solution/add-ons/hashicorp_vault_secrets/variables.tf
  caf_solution/add-ons/hashicorp_vault_secrets/vault.tf
Labels: enhancement

#213 bug fix for add-on remote states
  caf_solution/add-ons/hashicorp_vault_secrets/local.remote_tfstates.tf
  caf_solution/add-ons/hashicorp_vault_secrets/vault.tf
Labels: bug

#216 Add support for subscription_id_overrides_by_keys
  caf_solution/add-ons/caf_eslz/archetype_config_overrides.tf
  caf_solution/add-ons/caf_eslz/custom_landing_zones.tf
  caf_solution/add-ons/caf_eslz/enterprise_scale.tf
  caf_solution/add-ons/caf_eslz/locals.remote_tfstates.tf
  caf_solution/add-ons/caf_eslz/subscription_id_overrides.tf
  caf_solution/add-ons/caf_eslz/variables.tf
Labels: enhancement

#218 add variable object for storage account queues
  caf_solution/local.storage.tf
  caf_solution/variables.storage.tf
Labels: enhancement
