Repository Azure/caf-terraform-landingzones, pull requests merged in 2021-04, with the labels that each got.

#163 Missing tag in caf_solution
  caf_solution/landingzone.tf
Labels: bug

#161 Patch.5.3.1
  .devcontainer/docker-compose.yml
  .github/workflows/landingzones-tf13.yml
  .github/workflows/landingzones-tf14.yml
  .github/workflows/landingzones-tf15.yml
  caf_launchpad/dynamic_secrets.tf
  caf_launchpad/landingzone.tf
  caf_launchpad/main.tf
  caf_solution/add-ons/aad-pod-identity/main.tf
  caf_solution/add-ons/aks-secure-baseline/main.tf
  caf_solution/add-ons/azure_devops/locals.remote_tfstates.tf
  caf_solution/add-ons/azure_devops/main.tf
  caf_solution/add-ons/azure_devops/output.tf
  caf_solution/add-ons/azure_devops/solution.tf
  caf_solution/add-ons/azure_devops_agent/dynamic_secrets.tf
  caf_solution/add-ons/azure_devops_agent/locals.current_tfstates.tf
  caf_solution/add-ons/azure_devops_agent/main.tf
  caf_solution/add-ons/caf_eslz/custom_landing_zones.tf
  caf_solution/add-ons/caf_eslz/main.tf
  caf_solution/add-ons/caf_eslz/variables.tf
  caf_solution/add-ons/databricks/main.tf
  caf_solution/add-ons/terraform_cloud/main.tf
  caf_solution/dynamic_secrets.tf
  caf_solution/landingzone.tf
  caf_solution/main.tf
  caf_solution/variables.networking.tf
  caf_solution/variables.tf
Labels: bug, enhancement

#164 Patch.5.3.1
  caf_launchpad/dynamic_secrets.tf
  caf_launchpad/landingzone.tf
  caf_launchpad/main.tf
  caf_solution/add-ons/aad-pod-identity/providers.tf
  caf_solution/add-ons/aks-secure-baseline/main.tf
  caf_solution/add-ons/aks-secure-baseline/providers.tf
  caf_solution/add-ons/azure_devops/locals.remote_tfstates.tf
  caf_solution/add-ons/azure_devops/main.tf
  caf_solution/add-ons/azure_devops/output.tf
  caf_solution/add-ons/azure_devops_agent/dynamic_secrets.tf
  caf_solution/add-ons/azure_devops_agent/locals.current_tfstates.tf
  caf_solution/add-ons/azure_devops_agent/main.tf
  caf_solution/add-ons/azure_devops_agent/solution.tf
  caf_solution/add-ons/caf_eslz/custom_landing_zones.tf
  caf_solution/add-ons/databricks/main.tf
  caf_solution/add-ons/helm-charts/providers.tf
  caf_solution/add-ons/terraform_cloud/main.tf
  caf_solution/dynamic_secrets.tf
  caf_solution/landingzone.tf
  caf_solution/main.tf
  caf_solution/scenario/networking/200-single-region-hub/configuration.tfvars
  caf_solution/scenario/networking/201-multi-region-hub/configuration.tfvars
Labels: bug, enhancement

#165 Missing output for DevOps Agent Addon
  caf_solution/add-ons/azure_devops_agent/output.tf
Labels: bug

#166 added lighthouse variables
  caf_solution/local.remote.tf
  caf_solution/local.security.tf
  caf_solution/variables.security.tf
Labels: enhancement

#168 2104.1
  caf_solution/add-ons/aad-pod-identity/main.tf
  caf_solution/add-ons/aad-pod-identity/providers.tf
Labels: bug

#169 add waf policy
  caf_solution/add-ons/databricks/variables.tf
  caf_solution/local.networking.tf
  caf_solution/local.remote.tf
  caf_solution/variables.networking.tf
Labels: enhancement

#167 2104.2
  caf_solution/add-ons/aad-pod-identity/main.tf
  caf_solution/add-ons/aad-pod-identity/providers.tf
  caf_solution/add-ons/databricks/variables.tf
  caf_solution/local.networking.tf
  caf_solution/local.remote.tf
  caf_solution/local.security.tf
  caf_solution/variables.networking.tf
  caf_solution/variables.security.tf
Labels: enhancement

#172 2104.3
  caf_solution/add-ons/caf_eslz/archetype_config_overrides.tf
  caf_solution/add-ons/caf_eslz/custom_landing_zones.tf
  caf_solution/local.remote.tf
Labels: bug

#171 Update for WVD and ADO Agents add-on interim refactoring
  caf_solution/add-ons/azure_devops_agent/vm_extention_devops_agent.tf
  caf_solution/local.compute.tf
  caf_solution/variables.compute.tf
Labels: enhancement
