Repository Azure/caf-terraform-landingzones, pull requests merged in 2021-12, with the labels that each got.

#278 Add support for vmss custom script and domain join extensions
  .github/workflows/landingzones-tf100.yml
  caf_solution/vmss_extensions.tf
Labels: enhancement

#282 add remote support for ssl cert
  caf_solution/local.remote.tf
Labels: enhancement

#281 Add 'version' arg to aks_applications
  caf_solution/add-ons/aks_applications/app/module.tf
Labels: enhancement

#280 Add module for configuring SecretClass for CSI
  caf_solution/add-ons/secrets-store-csi-driver-provider-azure/README.md
  caf_solution/add-ons/secrets-store-csi-driver-provider-azure/backend.azurerm
  caf_solution/add-ons/secrets-store-csi-driver-provider-azure/build/kustomization_build.tf
  caf_solution/add-ons/secrets-store-csi-driver-provider-azure/build/main.tf
  caf_solution/add-ons/secrets-store-csi-driver-provider-azure/build/variables.tf
  caf_solution/add-ons/secrets-store-csi-driver-provider-azure/csi_keyvault_provider.tf
  caf_solution/add-ons/secrets-store-csi-driver-provider-azure/local.remote_tfstates.tf
  caf_solution/add-ons/secrets-store-csi-driver-provider-azure/main.tf
  caf_solution/add-ons/secrets-store-csi-driver-provider-azure/output.tf
  caf_solution/add-ons/secrets-store-csi-driver-provider-azure/providers.tf
  caf_solution/add-ons/secrets-store-csi-driver-provider-azure/secretproviderclass.yaml
  caf_solution/add-ons/secrets-store-csi-driver-provider-azure/variables.tf
Labels: enhancement

#262 Add support for CDN
  caf_solution/local.networking.tf
  caf_solution/variables.networking.tf
Labels: pending module update

#268 Service bus
  caf_solution/landingzone.tf
  caf_solution/local.remote.tf
  caf_solution/local.servicebus.tf
  caf_solution/variables.servicebus.tf
Labels: enhancement, pending module update

#264 Add support for Github service connections
  caf_solution/add-ons/azure_devops_v1/azdo_pipelines.tf
  caf_solution/add-ons/azure_devops_v1/azdo_service_endpoint.github.tf
  caf_solution/add-ons/azure_devops_v1/azdo_service_endpoint.tf
  caf_solution/add-ons/azure_devops_v1/readme.md
Labels: enhancement
