Repository Azure/caf-terraform-landingzones, pull requests merged in 2021-08, with the labels that each got.

#233 Fix subnet_keys role assignment for aks_secure_baseline_v2
  caf_solution/add-ons/aks_secure_baseline_v2/aks-pod-identity-assignment.tf
Labels: bug

#227 add vhub connection vnet id support
  caf_solution/add-ons/cross_tenant_hub_connection/hub_connection.tf
  caf_solution/add-ons/cross_tenant_hub_connection/scripts/wait.sh
Labels: enhancement

#238 Update aks-secure-baseline add-ons (V1 and V2) to support aks cluster with user assigned identity
  caf_solution/add-ons/aks-secure-baseline/aks-pod-identity-assignment.tf
  caf_solution/add-ons/aks_secure_baseline_v2/aks-pod-identity-assignment.tf
Labels: bug

#244 Update to support default global settings key
  caf_solution/locals.remote_tfstates.tf
Labels: enhancement

#243 Update readme and example for azuredevopsv1 add ons
  caf_solution/add-ons/azure_devops_v1/readme.md
  caf_solution/add-ons/azure_devops_v1/scenario/200-contoso_demo/agent_pools.tfvars
  caf_solution/add-ons/azure_devops_v1/scenario/200-contoso_demo/azure_devops.tfvars
  caf_solution/add-ons/azure_devops_v1/scenario/200-contoso_demo/configurations.tfvars
  caf_solution/add-ons/azure_devops_v1/scenario/200-contoso_demo/landingzone.tfvars
  caf_solution/add-ons/azure_devops_v1/scenario/200-contoso_demo/pipelines.tfvars
  caf_solution/add-ons/azure_devops_v1/scenario/200-contoso_demo/projects.tfvars
  caf_solution/add-ons/azure_devops_v1/scenario/200-contoso_demo/service_endpoints.tfvars
  caf_solution/add-ons/azure_devops_v1/scenario/200-contoso_demo/variable_groups.tfvars
Labels: documentation

#242 Adding vmware_clusters and vmware_private_cloud variables
  caf_solution/local.compute.tf
  caf_solution/local.remote.tf
  caf_solution/variables.compute.tf
  caf_solution/variables.tf
Labels: enhancement

#246 Update aks-pod-identity-assignment.tf
  caf_solution/add-ons/aks_secure_baseline_v2/aks-pod-identity-assignment.tf
Labels: enhancement

#236 Integration 5.4.2
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .github/workflows/landingzones-tf100.yml
  .github/workflows/landingzones-tf14.yml
  .github/workflows/landingzones-tf15.yml
  .pre-commit-config.yaml
  README.md
  caf_launchpad/dynamic_secrets.tf
  caf_launchpad/landingzone.tf
  caf_launchpad/scenario/100/storage_accounts.tfvars
  caf_launchpad/scenario/200/iam_role_mapping.tfvars
  caf_launchpad/scenario/200/storage_accounts.tfvars
  caf_solution/add-ons/aad-pod-identity/aad_pod_identity.tf
  caf_solution/add-ons/aks-secure-baseline/aks-pod-identity-assignment.tf
  caf_solution/add-ons/aks-secure-baseline/kustomization.yaml
  caf_solution/add-ons/aks_azure_devops_agents/kustomization.tf
  caf_solution/add-ons/aks_azure_devops_agents/locals.remote_tfstates.tf
  caf_solution/add-ons/aks_secure_baseline_v2/aks-pod-identity-assignment.tf
  caf_solution/add-ons/azure_devops/locals.remote_tfstates.tf
  caf_solution/add-ons/azure_devops_v1/readme.md
  caf_solution/add-ons/azure_devops_v1/scenario/200-contoso_demo/agent_pools.tfvars
  caf_solution/add-ons/azure_devops_v1/scenario/200-contoso_demo/azure_devops.tfvars
  caf_solution/add-ons/azure_devops_v1/scenario/200-contoso_demo/configurations.tfvars
  caf_solution/add-ons/azure_devops_v1/scenario/200-contoso_demo/landingzone.tfvars
  caf_solution/add-ons/azure_devops_v1/scenario/200-contoso_demo/pipelines.tfvars
  caf_solution/add-ons/azure_devops_v1/scenario/200-contoso_demo/projects.tfvars
  caf_solution/add-ons/azure_devops_v1/scenario/200-contoso_demo/service_endpoints.tfvars
  caf_solution/add-ons/azure_devops_v1/scenario/200-contoso_demo/variable_groups.tfvars
  caf_solution/add-ons/cross_tenant_hub_connection/hub_connection.tf
  caf_solution/add-ons/cross_tenant_hub_connection/scripts/wait.sh
  caf_solution/add-ons/hashicorp_vault_secrets/scenario/101-simple-hashicorp-vault-secret-backend-role/configuration.tfvars
  caf_solution/add-ons/hashicorp_vault_secrets/secret_backend_role/variables.tf
  caf_solution/add-ons/hashicorp_vault_secrets/secret_backend_role/vault_azure_secret_backend_role.tf
  caf_solution/add-ons/hashicorp_vault_secrets/vault.tf
  caf_solution/add-ons/hashicorp_vault_secrets/vault_azure_secret_backend_role.tf
  caf_solution/dynamic_secrets.tf
  caf_solution/landingzone.tf
  caf_solution/local.cognitive_services.tf
  caf_solution/local.compute.tf
  caf_solution/local.remote.tf
  caf_solution/locals.remote_tfstates.tf
  caf_solution/variables.cognitive_services.tf
  caf_solution/variables.compute.tf
  caf_solution/variables.tf
Labels: documentation, enhancement, devops
