Repository Azure/caf-terraform-landingzones, pull requests merged in 2021-09, with the labels that each got.

#252 fix baseline network scope role assignment
  caf_solution/add-ons/aks_secure_baseline_v2/aks-pod-identity-assignment.tf
Labels: bug

#255 fix a couple of broken links
  caf_launchpad/readme.md
  caf_solution/readme.md
Labels: documentation

#253 Auxiliary tenant is optional when peering in the same tenant
  caf_solution/add-ons/cross_tenant_hub_connection/providers.tf
Labels: enhancement

#251 Add variables to support for Virtual Network Link creation
  caf_solution/local.networking.tf
  caf_solution/variables.networking.tf
Labels: enhancement

#239 Support more resource type state in eslz
  caf_solution/add-ons/caf_eslz/locals.remote_tfstates.tf
Labels: enhancement
