Repository Azure/caf-terraform-landingzones, pull requests merged in 2022-03, with the labels that each got.

#296 Add domain_name_registrations to local.remote.tf
  caf_solution/local.remote.tf
Labels: enhancement, pending 5.5.2

#331 Fix typo in Rancher Desktop name
  documentation/getting_started/getting_started.md
Labels: documentation

#336 Deploy template library on initial setup with ignite
  caf_launchpad/documentation/variables.md
  caf_launchpad/scenario/100/configuration.tfvars
  caf_launchpad/scenario/200/configuration.tfvars
  caf_launchpad/scenario/200/diagnostics_destinations.tfvars
  caf_launchpad/variables.tf
  caf_solution/scenario/networking/105-hub-and-spoke/configuration.tfvars
  templates/ansible/load_deployments_alz.yaml
  templates/ansible/walk-through-single.yaml
  templates/platform/level0/launchpad/readme.md
  templates/platform/single_subscription.yaml
  templates/platform/template_topology.yaml
Labels: bug

#338 Added option for ADO agent to use full storage blob urls that are created outsiide of the same LZ
  caf_solution/add-ons/azure_devops_agent/scenario/200-contoso_demo/level0/virtual_machines.tfvars
  caf_solution/add-ons/azure_devops_agent/vm_extention_devops_agent.tf
Labels: 5.5.5

#333 Added sentinel
  caf_solution/local.remote.tf
  caf_solution/local.security.tf
  caf_solution/variables.security.tf
Labels: 5.5.5

#337 Add log analytics storage insights
  caf_solution/local.shared_services.tf
  caf_solution/variables.shared_services.tf
Labels: 5.5.5

#345 Fix Flux for public repo
  caf_solution/add-ons/aks_secure_baseline_v2/flux/flux.tf
Labels: bug
