Repository Azure/caf-terraform-landingzones, pull requests merged in 2022-04, with the labels that each got.

#358 Add support vhub route table routes
  caf_solution/local.networking.tf
  caf_solution/variables.networking.tf
Labels: 5.5.7

#357 Add Azure Batch Support
  caf_solution/local.compute.tf
  caf_solution/variables.compute.tf
Labels: 5.5.7

#341 blinQ - Add resource type public ip prefix
  caf_solution/local.networking.tf
  caf_solution/local.remote.tf
  caf_solution/variables.networking.tf
Labels: 5.5.6

#351 Add auth for ACR to aks_applications
  caf_solution/add-ons/aks_applications/app/module.tf
  caf_solution/add-ons/aks_applications/app/variables.tf
  caf_solution/add-ons/aks_applications/applications.tf
  caf_solution/add-ons/aks_applications/locals.remote_tfstates.tf
  caf_solution/add-ons/aks_applications/main.tf
Labels: enhancement
