Repository Azure/caf-terraform-landingzones, pull requests merged in 2022-05, with the labels that each got.

#303 Add support for configuring launchpad purge_soft_delete_on_destroy on Launchpad Key Vaults
  caf_launchpad/main.tf
  caf_launchpad/variables.tf
Labels: 5.5.9

#370 Add vnet_peerings_v1 - Better support vnet peerings between subscriptions
  caf_solution/local.networking.tf
  caf_solution/variables.networking.tf
Labels: enhancement, 5.5.9

#369 Adds azure container registry j2 resource template
  templates/resources/azure_container_registries.tfvars.j2
Labels: 5.5.9

#365 Adds application_security_groups to resource templates
  templates/resources/application_security_groups.tfvars.j2
Labels: 5.5.9

#364 Adds load_balancer resource template
  templates/resources/load_balancers.tfvars.j2
Labels: 5.5.9

#368 Adds bastion_hosts j2 resource template
  templates/resources/bastion_hosts.tfvars.j2
Labels: 5.5.9

#374 Updating Jinja templates and adding support for load balancers
  caf_launchpad/locals.remote_tfstates.tf
  caf_launchpad/main.tf
  caf_launchpad/output.tf
  caf_launchpad/variables.tf
  caf_solution/local.networking.tf
  caf_solution/local.remote.tf
  caf_solution/locals.remote_tfstates.tf
  caf_solution/main.tf
  caf_solution/output.tf
  caf_solution/variables.networking.tf
  caf_solution/variables.tf
  templates/ansible/action_plugins/__pycache__/merge_vars.cpython-39.pyc
  templates/ansible/ansible.yaml
  templates/ansible/walk-through-single.yaml
  templates/ansible/walk-through.yaml
  templates/platform/deploy_platform.sh
  templates/platform/level0/credentials/readme.md
  templates/platform/level0/launchpad/ansible.yaml
  templates/platform/level0/launchpad/keyvaults.tfvars.j2
  templates/platform/level0/launchpad/readme.md
  templates/platform/level1/alz/lib/v1.1.3/archetype_config_overrides.tfvars.j2
  templates/platform/level1/alz/lib/v1.1.3/custom_landing_zones.tfvars.j2
  templates/platform/level2/asvm/ansible.yaml
  templates/platform/level2/asvm/keyvaults.tfvars.j2
  templates/platform/level3/ansible.yaml
  templates/platform/services/README.md
  templates/platform/services/connectivity_private_dns.yaml
  templates/platform/services/connectivity_secure_firewalls.yaml
  templates/platform/services/gitops_agents_aci.yaml
  templates/platform/services/launchpad_azuread_sp_single_subscription.yaml
  templates/platform/services/management.yaml
  templates/platform/services/subscriptions.yaml
  templates/platform/single_subscription.yaml
  templates/resources/container_groups.tfvars.j2
  templates/resources/keyvaults.tfvars.j2
  templates/resources/network_acls.j2
  templates/resources/network_profiles.tfvars.j2
  templates/resources/storage_accounts.tfvars.j2
Labels: 5.5.9

#375 Update URL
  templates/platform/services/README.md
Labels: documentation

#377 Adding azurerm provider features as variables
  caf_launchpad/main.tf
  caf_launchpad/output.tf
  caf_launchpad/variables.provider.tf
  caf_launchpad/variables.tf
  caf_solution/add-ons/aks_secure_baseline_v2/flux/flux.tf
  caf_solution/add-ons/azure_devops_agent/vm_extention_devops_agent.tf
  caf_solution/main.tf
  caf_solution/output.tf
  caf_solution/variables.provider.tf
  caf_solution/variables.tf
Labels: enhancement
