Repository Azure/caf-terraform-landingzones, pull requests merged in 2022-06, with the labels that each got.

#388 Template updates
  templates/ansible/ansible.yaml
  templates/ansible/get_tfstate_content.yaml
  templates/ansible/load_variables.yaml
  templates/platform/generic/readme.md
  templates/platform/level0/launchpad/ansible.yaml
  templates/platform/level0/launchpad/keyvaults.tfvars.j2
  templates/platform/level0/launchpad/readme.md
  templates/platform/level1/alz/ansible.yaml
  templates/platform/level1/alz/lib/v1.1.3/archetype_config_overrides.tfvars.j2
  templates/platform/level1/alz/lib/v1.1.3/custom_landing_zones.tfvars.j2
  templates/platform/level1/alz/subscription_id_overrides.tfvars.j2
  templates/platform/level2/asvm/ansible.yaml
  templates/platform/level2/asvm/dynamic_secrets.tfvars.j2
  templates/platform/level2/asvm/keyvaults.tfvars.j2
  templates/platform/level2/asvm/role_mappings.tfvars.j2
  templates/platform/level2/connectivity/virtual_wans/readme.md
  templates/resources/azuread_groups_membership.tfvars.j2
  templates/resources/azurerm_firewall_policies.tfvars.j2
  templates/resources/keyvaults.tfvars.j2
  templates/resources/private_endpoints.tfvars.j2
  templates/resources/virtual_hub_connections.tfvars.j2
  templates/resources/virtual_hub_route_table_routes.tfvars.j2
Labels: enhancement, 5.6.0

#389 Add TFE backend support
  caf_launchpad/output.tf
  caf_solution/output.tf
  caf_solution/variables.tf
Labels: enhancement, 5.6.0

#382 Add support for packer_build module
  caf_solution/local.shared_services.tf
  caf_solution/variables.shared_services.tf
Labels: enhancement, 5.6.0

#383 Add missing local.remote.image_definitions
  caf_solution/local.remote.tf
Labels: 5.6.0

#385 Add new var: app_config_entries
  caf_solution/local.database.tf
  caf_solution/variables.database.tf
Labels: enhancement, 5.6.0

#393 Add support for for azurerm_log_analytics_linked_service to link automation account and log analytics workspace
  caf_solution/local.shared_services.tf
  caf_solution/variables.shared_services.tf
Labels: enhancement

#395 Add data_protection variable
  caf_solution/landingzone.tf
  caf_solution/local.data_protection.tf
  caf_solution/variables.data_protection.tf
Labels: 5.6.0
