Repository Azure/caf-terraform-landingzones, pull requests merged in 2023-08, with the labels that each got.

#484 aks_applications_v2 should work without AKS keyvault secret provider …
  caf_solution/add-ons/aks_applications_v2/locals.remote_tfstates.tf
Labels: bug

#489 Update landingzone.tf - changed var.logic_app to local.logic_app
  caf_solution/landingzone.tf
Labels: bug, logic_app

#490 Update for module 5.7.3
  caf_launchpad/dynamic_secrets.tf
  caf_launchpad/landingzone.tf
  caf_launchpad/main.tf
  caf_solution/dynamic_secrets.tf
  caf_solution/landingzone.tf
  caf_solution/main.tf
Labels: 5.7.3
